

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ricsanfre
          # URI to validate jwt
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8080

jwt:
  auth:
    converter:
      resource-id: ricsanfre-rest-api
      principal-attribute: preferred_username